-- SPDX-License-Identifier: AGPL-3.0-or-later
-- Copyright (c) 2026 林志荣
-- Generated by scripts/build-database-baseline.mjs; contains release metadata only.

\set ON_ERROR_STOP on

BEGIN;

DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM eiscore_meta.database_baselines
    WHERE baseline_id = 'eiscore-db-v1'
      AND (
        baseline_fingerprint_sha256 <> 'eaa3456dbe92d99a7a89bef4dc829dae873086e1f83fc64241051772ee827d5f'
        OR schema_sha256 <> 'dbcd35e8cc93254dd285a89a9fa210151a9490a60fa55cc287b2f566a7874a28'
        OR object_catalog_sha256 <> '596e8a54406314001a8788bb0f006da48f014d7e9c057aaa0ac19aa535d59265'
      )
  ) THEN
    RAISE EXCEPTION 'baseline identity conflict: eiscore-db-v1';
  END IF;

  IF EXISTS (
    SELECT 1
    FROM eiscore_meta.baseline_migration_coverage c
    JOIN (VALUES
  ('eiscore-db-v1', 'runtime-v2-001', '762ec169102bba3a016fafe8a72b486e89e9dd864e6de455e94a331dca001580', 'database/migrations/runtime-v2.json'),
  ('eiscore-db-v1', 'runtime-v2-002', 'd44540f9e039a2823d0b0705b7e8deb29c3f1d68d8977a83674c32bcb1bbc3b3', 'database/migrations/runtime-v2.json'),
  ('eiscore-db-v1', 'runtime-v2-003', '05df97b622b2e94637821af60750817dd86b8c375a703860f039f1fba28bfcfc', 'database/migrations/runtime-v2.json'),
  ('eiscore-db-v1', 'runtime-v2-004', 'acf9d0ecd5920cc6385a47c79c8236823d3f22fc2bb5b36195031889d0ee4bdf', 'database/migrations/runtime-v2.json'),
  ('eiscore-db-v1', 'runtime-v2-005', '2040bf34351ee6bcaa9ca196ec70c74a1f83d587436b7bb574ad1da70db1278b', 'database/migrations/runtime-v2.json'),
  ('eiscore-db-v1', 'runtime-v2-006', 'ba4eb04ef6a7e19f7f8b05961f8101391715000014faea37a5f55e64fa67107d', 'database/migrations/runtime-v2.json'),
  ('eiscore-db-v1', 'runtime-v2-007', '378ed86f77cef6958cdd89256f70c55c2611ee8cd64245216165a55a2c2856c7', 'database/migrations/runtime-v2.json'),
  ('eiscore-db-v1', 'runtime-v2-008', '6386919b81b1b3772063bdafb4ef3058e37fec2d915811d24494221d053f531c', 'database/migrations/runtime-v2.json'),
  ('eiscore-db-v1', 'runtime-v2-009', '72a89d592c2ea26d429f7a04d0b63addc9ad02839164588eb3f75314c739f9f6', 'database/migrations/runtime-v2.json'),
  ('eiscore-db-v1', 'runtime-v2-010', 'aa6758a6e1043a2680a9464da35fd864706b1cdc4882c5f4d29bc60dc6bf39d4', 'database/migrations/runtime-v2.json'),
  ('eiscore-db-v1', 'company-site-001', '6fe9262a5d59da7962546121136d0629f2e9f23e5dca06bbed7a6497aaee25d4', 'database/migrations/company-site.json'),
  ('eiscore-db-v1', 'core-001', '70ff80d137a15f3312eb8fdce5e1b25157cb43f0013a7c03ab03e83086cd4ffc', 'database/migrations/core.json')
    ) AS expected(baseline_id, migration_id, checksum_sha256, source_manifest)
      ON expected.baseline_id = c.baseline_id
     AND expected.migration_id = c.migration_id
    WHERE c.checksum_sha256 <> expected.checksum_sha256
       OR c.source_manifest <> expected.source_manifest
  ) THEN
    RAISE EXCEPTION 'baseline migration coverage checksum conflict: eiscore-db-v1';
  END IF;
END
$$;

INSERT INTO eiscore_meta.database_baselines (
  baseline_id,
  baseline_fingerprint_sha256,
  schema_sha256,
  object_catalog_sha256
) VALUES (
  'eiscore-db-v1',
  'eaa3456dbe92d99a7a89bef4dc829dae873086e1f83fc64241051772ee827d5f',
  'dbcd35e8cc93254dd285a89a9fa210151a9490a60fa55cc287b2f566a7874a28',
  '596e8a54406314001a8788bb0f006da48f014d7e9c057aaa0ac19aa535d59265'
)
ON CONFLICT (baseline_id) DO NOTHING;

INSERT INTO eiscore_meta.baseline_migration_coverage (
  baseline_id,
  migration_id,
  checksum_sha256,
  source_manifest
) VALUES
  ('eiscore-db-v1', 'runtime-v2-001', '762ec169102bba3a016fafe8a72b486e89e9dd864e6de455e94a331dca001580', 'database/migrations/runtime-v2.json'),
  ('eiscore-db-v1', 'runtime-v2-002', 'd44540f9e039a2823d0b0705b7e8deb29c3f1d68d8977a83674c32bcb1bbc3b3', 'database/migrations/runtime-v2.json'),
  ('eiscore-db-v1', 'runtime-v2-003', '05df97b622b2e94637821af60750817dd86b8c375a703860f039f1fba28bfcfc', 'database/migrations/runtime-v2.json'),
  ('eiscore-db-v1', 'runtime-v2-004', 'acf9d0ecd5920cc6385a47c79c8236823d3f22fc2bb5b36195031889d0ee4bdf', 'database/migrations/runtime-v2.json'),
  ('eiscore-db-v1', 'runtime-v2-005', '2040bf34351ee6bcaa9ca196ec70c74a1f83d587436b7bb574ad1da70db1278b', 'database/migrations/runtime-v2.json'),
  ('eiscore-db-v1', 'runtime-v2-006', 'ba4eb04ef6a7e19f7f8b05961f8101391715000014faea37a5f55e64fa67107d', 'database/migrations/runtime-v2.json'),
  ('eiscore-db-v1', 'runtime-v2-007', '378ed86f77cef6958cdd89256f70c55c2611ee8cd64245216165a55a2c2856c7', 'database/migrations/runtime-v2.json'),
  ('eiscore-db-v1', 'runtime-v2-008', '6386919b81b1b3772063bdafb4ef3058e37fec2d915811d24494221d053f531c', 'database/migrations/runtime-v2.json'),
  ('eiscore-db-v1', 'runtime-v2-009', '72a89d592c2ea26d429f7a04d0b63addc9ad02839164588eb3f75314c739f9f6', 'database/migrations/runtime-v2.json'),
  ('eiscore-db-v1', 'runtime-v2-010', 'aa6758a6e1043a2680a9464da35fd864706b1cdc4882c5f4d29bc60dc6bf39d4', 'database/migrations/runtime-v2.json'),
  ('eiscore-db-v1', 'company-site-001', '6fe9262a5d59da7962546121136d0629f2e9f23e5dca06bbed7a6497aaee25d4', 'database/migrations/company-site.json'),
  ('eiscore-db-v1', 'core-001', '70ff80d137a15f3312eb8fdce5e1b25157cb43f0013a7c03ab03e83086cd4ffc', 'database/migrations/core.json')
ON CONFLICT (baseline_id, migration_id) DO NOTHING;

DO $$
BEGIN
  IF (
    SELECT count(*)
    FROM eiscore_meta.baseline_migration_coverage
    WHERE baseline_id = 'eiscore-db-v1'
  ) <> 12 THEN
    RAISE EXCEPTION 'baseline migration coverage conflict: eiscore-db-v1';
  END IF;
END
$$;

COMMIT;
